name: Rust

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run tests
        run: cargo test --verbose

  release:
    needs: [test]

    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            rust: stable
            bin: questionnaire
            name: questionnaire-Linux-x86_64.tar.gz

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          target: ${{ matrix.target }}

      - name: Run build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Package
        shell: bash
        run: |
          strip target/release/${{ matrix.bin }}
          cd target/release
          tar czvf ../../../${{ matrix.name }} ${{ matrix.bin }}
          cd -

      - name: Publish
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "questionnaire*"
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
